name: Deploy to Cloud Run

on:
  pull_request:
    types: [closed]

permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  test:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: echo "No tests configured"
  deploy:
    needs: test
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          IMAGE_URL: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/guesswho/guesswhoservice:${{ github.sha }}
        run: |
          cd guesswhoservice
          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy guesswhoservice \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/guesswho/guesswhoservice:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated